"""empty message

<<<<<<< HEAD:migrations/versions/4d9f50c1b156_.py
<<<<<<<< HEAD:migrations/versions/a03915efdec4_.py
Revision ID: a03915efdec4
Revises: 
Create Date: 2023-09-20 12:28:41.837532
========
Revision ID: 4d9f50c1b156
Revises: 
Create Date: 2023-09-20 12:25:24.846403
>>>>>>>> 914bb985004c9acfd0b12e39bd97b589c2cd2439:migrations/versions/4d9f50c1b156_.py
=======
Revision ID: 48d70e909b29
Revises: 
Create Date: 2023-09-20 13:46:47.395749
>>>>>>> 99f02605985046e724b6a8389ce709e9f9d73e6f:migrations/versions/48d70e909b29_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/4d9f50c1b156_.py
<<<<<<<< HEAD:migrations/versions/a03915efdec4_.py
revision = 'a03915efdec4'
========
revision = '4d9f50c1b156'
>>>>>>>> 914bb985004c9acfd0b12e39bd97b589c2cd2439:migrations/versions/4d9f50c1b156_.py
=======
revision = '48d70e909b29'
>>>>>>> 99f02605985046e724b6a8389ce709e9f9d73e6f:migrations/versions/48d70e909b29_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('lastname', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('profile_picture', sa.String(length=300), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('account_creation_date', sa.String(length=40), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('house',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=10), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('number_of_rooms', sa.Integer(), nullable=False),
    sa.Column('number_of_bathrooms', sa.Integer(), nullable=False),
    sa.Column('parking', sa.Boolean(), nullable=False),
    sa.Column('wifi', sa.Boolean(), nullable=False),
    sa.Column('virified_account', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.Column('date_of_admission', sa.String(length=100), nullable=False),
    sa.Column('date_of_delivery', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.drop_table('favorites')
    op.drop_table('booking')
    op.drop_table('house')
    op.drop_table('user')
    # ### end Alembic commands ###
